<?php

return [
    'quick_starts' => [
        [
            'title' => 'Set up a portfolio',
            'audience' => 'Superadmin',
            'roles' => ['superadmin'],
            'route' => '/portfolios',
            'summary' => 'Create the owner boundary first. Every user, asset, tenant, lease, payment, and report hangs off that portfolio.',
            'steps' => ['Create portfolio', 'Create owner account', 'Assign manager', 'Seed buildings and units'],
            'tags' => ['portfolio', 'owner', 'setup'],
            'icon' => 'bi-buildings',
        ],
        [
            'title' => 'Create a rentable asset tree',
            'audience' => 'Owner',
            'roles' => ['superadmin', 'owner'],
            'route' => '/assets/building-setup',
            'summary' => 'Create a complete building, its floors, and numbered rental units in one guided transaction.',
            'steps' => ['Name the building', 'Choose floor and unit counts', 'Assign owner and manager', 'Review and create the structure'],
            'tags' => ['assets', 'floors', 'units'],
            'icon' => 'bi-diagram-3',
        ],
        [
            'title' => 'Onboard a tenant',
            'audience' => 'Owner / Manager',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'route' => '/tenants/create?next=lease',
            'summary' => 'Start from a vacant rental or create the tenant directly. The system carries the tenant and selected unit into a draft lease.',
            'steps' => ['Choose vacant rental', 'Add or select tenant', 'Create draft lease', 'Upload signed contract'],
            'tags' => ['tenant', 'lease', 'contract'],
            'icon' => 'bi-person-badge',
        ],
        [
            'title' => 'Track payment health',
            'audience' => 'Owner / Finance',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'route' => '/rent-collection',
            'summary' => 'Post manual payments against a lease so balances, arrears, receipts, and reports stay accurate.',
            'steps' => ['Open lease', 'Post payment', 'Generate receipt', 'Review arrears report'],
            'tags' => ['payments', 'rent', 'arrears'],
            'icon' => 'bi-cash-stack',
        ],
        [
            'title' => 'Use the tenant portal',
            'audience' => 'Tenant',
            'roles' => ['tenant'],
            'route' => '/dashboard',
            'summary' => 'Start from the tenant dashboard to check rent, contract dates, documents, receipts, and maintenance requests.',
            'steps' => ['Open dashboard', 'Download contract', 'Review payment history', 'Submit maintenance request'],
            'tags' => ['tenant', 'contract', 'maintenance'],
            'icon' => 'bi-person-check',
        ],
    ],
    'workflows' => [
        [
            'key' => 'portfolio_launch',
            'title' => 'Launch a managed portfolio',
            'audience' => 'Superadmin / Owner',
            'roles' => ['superadmin', 'owner'],
            'route' => '/portfolios',
            'icon' => 'bi-rocket-takeoff',
            'summary' => 'Start with the client boundary, then add the people and modules that can operate inside it.',
            'outcome' => 'A portfolio with owner, manager, module permissions, and a clean starting point for assets.',
            'steps' => [
                ['label' => 'Create portfolio', 'route' => '/portfolios', 'module' => null],
                ['label' => 'Create owner and manager users', 'route' => '/users', 'module' => 'users'],
                ['label' => 'Enable only needed modules', 'route' => '/portfolios', 'module' => null],
                ['label' => 'Open documentation for the owner', 'route' => '/documentation', 'module' => null],
            ],
        ],
        [
            'key' => 'daily_operations',
            'title' => 'Run the daily property action queue',
            'audience' => 'Owner / Manager',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'route' => '/action-center',
            'icon' => 'bi-collection',
            'summary' => 'Start from one prioritized list instead of checking collections, maintenance, renewals, and move-outs separately.',
            'outcome' => 'Critical work is handled first, every item has a responsible person, and property teams know exactly where to continue.',
            'steps' => [
                ['label' => 'Open the Action Center', 'route' => '/action-center', 'module' => null],
                ['label' => 'Clear critical and overdue items', 'route' => '/action-center?priority=critical', 'module' => null],
                ['label' => 'Assign unowned work', 'route' => '/action-center?assignee=unassigned', 'module' => null],
                ['label' => 'Export the current queue for review', 'route' => '/action-center', 'module' => null],
            ],
        ],
        [
            'key' => 'asset_to_lease',
            'title' => 'Turn a property into a rent-ready lease',
            'audience' => 'Owner / Manager',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'route' => '/assets',
            'icon' => 'bi-diagram-3',
            'summary' => 'Build the property tree, open the vacant rentable unit, then start its tenancy without searching for that unit again.',
            'outcome' => 'The selected unit, portfolio, tenant profile, draft lease, contract, and move-in checklist stay connected.',
            'steps' => [
                ['label' => 'Set up or extend the building structure', 'route' => '/assets', 'module' => 'assets'],
                ['label' => 'Open a vacant rentable unit', 'route' => '/assets?occupancy_status=vacant', 'module' => 'assets'],
                ['label' => 'Choose an existing tenant or add a new one', 'route' => '/leases/create', 'module' => 'leases'],
                ['label' => 'Create the draft and complete move-in', 'route' => '/leases', 'module' => 'leases'],
            ],
        ],
        [
            'key' => 'rent_collection',
            'title' => 'Collect rent without losing the audit trail',
            'audience' => 'Owner / Finance',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'route' => '/payments',
            'icon' => 'bi-cash-stack',
            'summary' => 'Work from the installment, record each tenant contact, assign the next follow-up, then post the real payment against the lease.',
            'outcome' => 'Rent due, collection ownership, promises, paid amounts, arrears, receipts, and owner reports stay accountable and match the lease installments.',
            'steps' => [
                ['label' => 'Open the collection ledger', 'route' => '/rent-collection', 'module' => 'payments'],
                ['label' => 'Record contact and next follow-up', 'route' => '/rent-collection', 'module' => 'payments'],
                ['label' => 'Post manual payment', 'route' => '/payments', 'module' => 'payments'],
                ['label' => 'Download receipt', 'route' => '/payments', 'module' => 'payments'],
                ['label' => 'Review arrears report', 'route' => '/reports', 'module' => 'reports'],
            ],
        ],
        [
            'key' => 'owner_statement',
            'title' => 'Prepare an owner statement',
            'audience' => 'Owner / Manager',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'route' => '/reports/statement',
            'icon' => 'bi-file-earmark-bar-graph',
            'summary' => 'Choose the reporting period and property once, review the owner-ready figures, then download the same scoped data as PDF or Word.',
            'outcome' => 'A concise bilingual statement covering collections, costs, arrears, occupancy, and open maintenance without exposing another portfolio.',
            'steps' => [
                ['label' => 'Set the period and property in Reports', 'route' => '/reports', 'module' => 'reports'],
                ['label' => 'Open the owner statement', 'route' => '/reports/statement', 'module' => 'reports'],
                ['label' => 'Review the financial and operational cards', 'route' => '/reports/statement', 'module' => 'reports'],
                ['label' => 'Download PDF or Word', 'route' => '/reports/statement', 'module' => 'reports'],
            ],
        ],
        [
            'key' => 'lease_move_out',
            'title' => 'Close a tenancy without losing the handover trail',
            'audience' => 'Owner / Manager',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'route' => '/lease-move-outs',
            'icon' => 'bi-box-arrow-right',
            'summary' => 'Plan the departure first, then prove notice, inspection, keys, and deposit decisions before releasing the asset.',
            'outcome' => 'A vacant asset with signed PDF evidence, an auditable handover, and any unpaid balance still collectible.',
            'steps' => [
                ['label' => 'Plan the move-out date', 'route' => '/lease-move-outs', 'module' => 'leases'],
                ['label' => 'Upload notice and inspection PDFs', 'route' => '/documents', 'module' => 'documents'],
                ['label' => 'Record keys and deposit decision', 'route' => '/lease-move-outs', 'module' => 'leases'],
                ['label' => 'Complete handover and collect final balance', 'route' => '/rent-collection', 'module' => 'payments'],
            ],
        ],
        [
            'key' => 'service_request',
            'title' => 'Run maintenance from tenant request to cost',
            'audience' => 'Tenant / Manager',
            'roles' => ['superadmin', 'owner', 'property_manager', 'tenant'],
            'route' => '/maintenance-requests',
            'icon' => 'bi-tools',
            'summary' => 'Tenants submit the issue; managers triage priority, public updates, internal notes, assignment, and cost.',
            'outcome' => 'Every service request has status, due date, tenant-visible history, private operations notes, and expense impact.',
            'steps' => [
                ['label' => 'Tenant submits request', 'route' => '/maintenance-requests', 'module' => 'maintenance'],
                ['label' => 'Manager assigns priority', 'route' => '/maintenance-requests', 'module' => 'maintenance'],
                ['label' => 'Share public update', 'route' => '/maintenance-requests', 'module' => 'maintenance'],
                ['label' => 'Record expense and close', 'route' => '/expenses', 'module' => 'expenses'],
            ],
        ],
        [
            'key' => 'website_publish',
            'title' => 'Publish the public website safely',
            'audience' => 'Superadmin',
            'roles' => ['superadmin'],
            'route' => '/cms',
            'icon' => 'bi-window-stack',
            'summary' => 'Use reusable bilingual sections, drag them into order, preview, then publish. No raw script chaos.',
            'outcome' => 'A bilingual landing page with header navigation, SEO fields, media, and visible portal calls to action.',
            'steps' => [
                ['label' => 'Create page', 'route' => '/cms', 'module' => null],
                ['label' => 'Attach sections', 'route' => '/cms', 'module' => null],
                ['label' => 'Drag sections into order', 'route' => '/cms', 'module' => null],
                ['label' => 'Preview and publish', 'route' => '/cms', 'module' => null],
            ],
        ],
    ],
    'page_shortcuts' => [
        [
            'label' => 'Dashboard',
            'category' => 'Command',
            'route' => '/dashboard',
            'description' => 'Start here for KPIs, alerts, next actions, and today\'s operating picture.',
            'action' => 'Open control center',
            'icon' => 'bi-grid-1x2',
        ],
        [
            'label' => 'Portfolio Control',
            'category' => 'Command',
            'route' => '/portfolio-control',
            'description' => 'Compare every accessible property, rank operating pressure, and continue directly into the focused dashboard, Action Center, or reports.',
            'action' => 'Compare properties',
            'icon' => 'bi-buildings',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'module' => 'assets',
        ],
        [
            'label' => 'Action Center',
            'category' => 'Command',
            'route' => '/action-center',
            'description' => 'Work collections, maintenance, renewals, and move-outs from one property-scoped priority queue.',
            'action' => 'Open daily queue',
            'icon' => 'bi-collection',
            'roles' => ['superadmin', 'owner', 'property_manager'],
        ],
        [
            'label' => 'Portfolios',
            'category' => 'Setup',
            'route' => '/portfolios',
            'description' => 'Create the client boundary, assign owner, and control module visibility.',
            'action' => 'Manage portfolio',
            'icon' => 'bi-buildings',
            'roles' => ['superadmin', 'owner', 'property_manager'],
        ],
        [
            'label' => 'Users',
            'category' => 'Setup',
            'route' => '/users',
            'description' => 'Create owner, manager, and tenant accounts with role-specific access.',
            'action' => 'Manage users',
            'icon' => 'bi-people',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'module' => 'users',
        ],
        [
            'label' => 'Assets',
            'category' => 'Portfolio',
            'route' => '/assets',
            'description' => 'Build buildings, floors, units, spaces, values, and ownership/management assignments.',
            'action' => 'Control assets',
            'icon' => 'bi-diagram-3',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'module' => 'assets',
        ],
        [
            'label' => 'Building Setup',
            'category' => 'Portfolio',
            'route' => '/assets/building-setup',
            'description' => 'Create a building, its floors, and numbered rental units in one guided transaction.',
            'action' => 'Set up building',
            'icon' => 'bi-buildings',
            'roles' => ['superadmin', 'owner'],
            'module' => 'assets',
        ],
        [
            'label' => 'Tenants',
            'category' => 'Portfolio',
            'route' => '/tenants',
            'description' => 'Create tenant profiles, portal identities, contacts, and onboarding records.',
            'action' => 'Open tenants',
            'icon' => 'bi-person-badge',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'module' => 'tenants',
        ],
        [
            'label' => 'Leases',
            'category' => 'Contracts',
            'route' => '/leases',
            'description' => 'Create contracts, generate PDFs, upload signed files, and track installment balances.',
            'action' => 'Manage leases',
            'icon' => 'bi-file-earmark-text',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'module' => 'leases',
        ],
        [
            'label' => 'Move-outs',
            'category' => 'Contracts',
            'route' => '/lease-move-outs',
            'description' => 'Control notices, inspections, keys, deposits, final balances, and unit handover.',
            'action' => 'Open move-out queue',
            'icon' => 'bi-box-arrow-right',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'module' => 'leases',
        ],
        [
            'label' => 'Payments',
            'category' => 'Finance',
            'route' => '/payments',
            'description' => 'Post manual rent, generate receipts, and keep arrears tied to lease installments.',
            'action' => 'Post payment',
            'icon' => 'bi-receipt',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'module' => 'payments',
        ],
        [
            'label' => 'Maintenance',
            'category' => 'Service',
            'route' => '/maintenance-requests',
            'description' => 'Submit, triage, update, assign, and close tenant service requests.',
            'action' => 'Open queue',
            'icon' => 'bi-tools',
            'module' => 'maintenance',
        ],
        [
            'label' => 'Reports',
            'category' => 'Control',
            'route' => '/reports',
            'description' => 'Review revenue, expenses, arrears, and occupancy, then export XLSX workbooks or bilingual owner statements.',
            'action' => 'Open reports',
            'icon' => 'bi-graph-up-arrow',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'module' => 'reports',
        ],
        [
            'label' => 'Website Control',
            'category' => 'Website',
            'route' => '/cms',
            'description' => 'Build bilingual public pages with draggable sections, media, SEO, and navigation.',
            'action' => 'Open builder',
            'icon' => 'bi-layout-wtf',
            'roles' => ['superadmin'],
        ],
    ],
    'control_checks' => [
        [
            'title' => 'Portfolio isolation',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'summary' => 'Owners and managers must only see users, assets, tenants, leases, payments, documents, and reports inside their portfolio.',
            'route' => '/audit-logs',
            'icon' => 'bi-shield-check',
            'checks' => ['Owner A cannot search Owner B assets', 'XLSX exports use the same scope as tables', 'Global search hides disabled modules'],
        ],
        [
            'title' => 'Tenant privacy',
            'roles' => ['superadmin', 'owner', 'property_manager', 'tenant'],
            'summary' => 'Tenants see only their lease, payments, documents, and maintenance history. Internal notes stay private.',
            'route' => '/maintenance-requests',
            'icon' => 'bi-person-lock',
            'checks' => ['Tenant cannot open another lease', 'Private maintenance notes are hidden', 'Receipts require authorized access'],
        ],
        [
            'title' => 'Financial traceability',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'module' => 'reports',
            'summary' => 'Payments, allocations, installments, receipts, expenses, and reports must reconcile back to the lease.',
            'route' => '/reports',
            'icon' => 'bi-calculator',
            'checks' => ['Payment allocation updates balance', 'Voids do not erase history', 'Expenses roll into net revenue'],
        ],
        [
            'title' => 'Website publishing safety',
            'roles' => ['superadmin'],
            'summary' => 'Only superadmin controls global public pages. The builder allows predefined sections, not arbitrary script injection.',
            'route' => '/cms',
            'icon' => 'bi-shield-check',
            'checks' => ['Draft pages stay private', 'Section reorder persists', 'Arabic/English content renders with correct direction'],
        ],
    ],
    'role_guides' => [
        [
            'role' => 'superadmin',
            'title' => 'System owner',
            'summary' => 'Owns the platform-level setup, website, global users, portfolio oversight, and audit trail.',
            'responsibilities' => ['Control public website', 'Create portfolios', 'Monitor platform totals', 'Audit permissions and content'],
            'routes' => ['/dashboard', '/portfolios', '/users', '/cms', '/reports'],
            'icon' => 'bi-shield-lock',
        ],
        [
            'role' => 'owner',
            'title' => 'Property owner',
            'summary' => 'Controls their portfolio lifecycle from assets to tenants, leases, payments, maintenance, and reports.',
            'responsibilities' => ['Manage portfolio assets', 'Create tenants and leases', 'Track payments', 'Review maintenance and reports'],
            'routes' => ['/dashboard', '/portfolio-control', '/assets', '/tenants', '/leases', '/payments', '/maintenance-requests'],
            'icon' => 'bi-buildings',
        ],
        [
            'role' => 'property_manager',
            'title' => 'Property manager',
            'summary' => 'Runs day-to-day portfolio operations, tenant service, rent posting, and maintenance triage.',
            'responsibilities' => ['Run daily asset operations', 'Handle tenants', 'Post payments', 'Triage maintenance'],
            'routes' => ['/portfolio-control', '/assets', '/tenants', '/leases', '/payments', '/maintenance-requests'],
            'icon' => 'bi-person-workspace',
        ],
        [
            'role' => 'tenant',
            'title' => 'Tenant',
            'summary' => 'Uses a restricted portal for contract status, payment visibility, documents, and maintenance requests.',
            'responsibilities' => ['View contract status', 'Download documents', 'Track paid and remaining rent', 'Submit maintenance requests'],
            'routes' => ['/dashboard', '/maintenance-requests'],
            'icon' => 'bi-person-badge',
        ],
    ],
    'guides' => [
        [
            'title' => 'Asset Control',
            'audience' => 'Owner / Manager',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'route' => '/assets',
            'summary' => 'Assets are a tree. A tenant can rent a building, floor, unit, or space when that node is marked rentable.',
            'features' => ['Property/building/floor/unit hierarchy', 'Ownership and management assignment', 'Valuation and usage tracking', 'Occupancy state'],
            'steps' => ['Create the parent building', 'Add floors, units, and spaces below it', 'Mark only rentable nodes as rentable', 'Assign primary owner and manager'],
            'rules' => ['Keep codes unique', 'Do not mark parent buildings rentable unless leasing the whole building', 'Only assign managers from the same portfolio'],
            'icon' => 'bi-building',
        ],
        [
            'title' => 'Lease Lifecycle',
            'audience' => 'Owner / Manager',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'route' => '/leases',
            'summary' => 'Leases connect a tenant to a rentable asset and generate installment balances.',
            'features' => ['Contract PDF', 'Signed upload', 'Installment generation', 'Days remaining and balance remaining'],
            'steps' => ['Create or select a tenant', 'Choose a rentable asset', 'Set rent, deposit, dates, and billing day', 'Generate the contract and installments'],
            'rules' => ['One active lease per rentable asset in v1', 'Payments should be posted to the lease, not the tenant only'],
            'icon' => 'bi-file-earmark-text',
        ],
        [
            'title' => 'Move-out Handover',
            'audience' => 'Owner / Manager',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'route' => '/lease-move-outs',
            'summary' => 'Move-out is a controlled handover, not a delete button. Required evidence protects the owner, tenant, and asset record.',
            'features' => ['Portfolio move-out queue', 'Notice and inspection PDFs', 'Keys and deposit decision', 'Final balance preservation'],
            'steps' => ['Open the lease and plan move-out', 'Upload the termination notice PDF', 'Upload the move-out inspection PDF', 'Record keys and deposit decision, then complete'],
            'rules' => ['Do not complete before the move-out date', 'Never erase unpaid rent during handover', 'Use PDF evidence for signed notice and inspection'],
            'icon' => 'bi-box-arrow-right',
        ],
        [
            'title' => 'Payments And Receipts',
            'audience' => 'Owner / Finance',
            'roles' => ['superadmin', 'owner', 'property_manager'],
            'route' => '/payments',
            'summary' => 'Payments are manual in v1. Posting a payment allocates it to lease installments and feeds reports.',
            'features' => ['Rent/deposit/payment type', 'Payment method', 'Receipt PDF', 'Arrears tracking'],
            'steps' => ['Open Payments', 'Select the lease and tenant', 'Enter amount, method, date, and reference', 'Save and review the allocation in reports'],
            'rules' => ['Void bad payments instead of deleting history', 'Use references for bank transfer reconciliation'],
            'icon' => 'bi-receipt',
        ],
        [
            'title' => 'Maintenance Requests',
            'audience' => 'Tenant / Manager',
            'roles' => ['superadmin', 'owner', 'property_manager', 'tenant'],
            'route' => '/maintenance-requests',
            'summary' => 'Tenants submit service requests. Owners and managers triage status, priority, assignment, notes, and cost.',
            'features' => ['Electrical/plumbing/general categories', 'Priority and status', 'Public tenant updates', 'Expense linkage'],
            'steps' => ['Tenant submits the issue', 'Owner or manager sets priority and status', 'Add public updates for the tenant', 'Record expenses and close after resolution'],
            'rules' => ['Keep internal notes private', 'Close only after tenant-visible resolution is recorded'],
            'icon' => 'bi-tools',
        ],
        [
            'title' => 'Website Control',
            'audience' => 'Superadmin',
            'roles' => ['superadmin'],
            'route' => '/cms',
            'summary' => 'The public website is made of pages, sections, menus, and media. Sections can be reordered visually.',
            'features' => ['Bilingual pages', 'Section library', 'Drag and drop ordering', 'Header navigation'],
            'steps' => ['Create or select a page', 'Create reusable bilingual sections', 'Attach sections to the page', 'Drag sections to reorder and preview'],
            'rules' => ['Only superadmin controls the global website', 'Use predefined sections instead of raw scripts'],
            'icon' => 'bi-layout-wtf',
        ],
    ],
];
