<?php

return [
    'quick_starts' => [
        [
            'title' => 'Set up a portfolio',
            'audience' => 'Superadmin',
            'route' => '/portfolios',
            'summary' => 'Create the owner boundary first. Every user, asset, tenant, lease, payment, and report hangs off that portfolio.',
            'steps' => ['Create portfolio', 'Create owner account', 'Assign manager', 'Seed buildings and units'],
            'tags' => ['portfolio', 'owner', 'setup'],
            'icon' => 'bi-buildings',
        ],
        [
            'title' => 'Create a rentable asset tree',
            'audience' => 'Owner / Manager',
            'route' => '/assets',
            'summary' => 'Build from property to building to floor to unit. Mark only rentable nodes as rentable.',
            'steps' => ['Add building', 'Add floors', 'Add units/spaces', 'Assign owner and manager'],
            'tags' => ['assets', 'floors', 'units'],
            'icon' => 'bi-diagram-3',
        ],
        [
            'title' => 'Onboard a tenant',
            'audience' => 'Owner / Manager',
            'route' => '/tenants',
            'summary' => 'Create the tenant profile and portal account before creating the lease.',
            'steps' => ['Create tenant', 'Add contact details', 'Create lease', 'Upload signed contract'],
            'tags' => ['tenant', 'lease', 'contract'],
            'icon' => 'bi-person-badge',
        ],
        [
            'title' => 'Track payment health',
            'audience' => 'Owner / Finance',
            'route' => '/payments',
            'summary' => 'Post manual payments against a lease so balances, arrears, receipts, and reports stay accurate.',
            'steps' => ['Open lease', 'Post payment', 'Generate receipt', 'Review arrears report'],
            'tags' => ['payments', 'rent', 'arrears'],
            'icon' => 'bi-cash-stack',
        ],
    ],
    'role_guides' => [
        [
            'role' => 'superadmin',
            'title' => 'System owner',
            'summary' => 'Owns the platform-level setup, website, global users, portfolio oversight, and audit trail.',
            'responsibilities' => ['Control public website', 'Create portfolios', 'Monitor platform totals', 'Audit permissions and content'],
            'routes' => ['/dashboard', '/portfolios', '/users', '/cms', '/reports'],
            'icon' => 'bi-shield-lock',
        ],
        [
            'role' => 'owner',
            'title' => 'Property owner',
            'summary' => 'Controls their portfolio lifecycle from assets to tenants, leases, payments, maintenance, and reports.',
            'responsibilities' => ['Manage portfolio assets', 'Create tenants and leases', 'Track payments', 'Review maintenance and reports'],
            'routes' => ['/dashboard', '/assets', '/tenants', '/leases', '/payments', '/maintenance-requests'],
            'icon' => 'bi-buildings',
        ],
        [
            'role' => 'property_manager',
            'title' => 'Property manager',
            'summary' => 'Runs day-to-day portfolio operations, tenant service, rent posting, and maintenance triage.',
            'responsibilities' => ['Run daily asset operations', 'Handle tenants', 'Post payments', 'Triage maintenance'],
            'routes' => ['/assets', '/tenants', '/leases', '/payments', '/maintenance-requests'],
            'icon' => 'bi-person-workspace',
        ],
        [
            'role' => 'tenant',
            'title' => 'Tenant',
            'summary' => 'Uses a restricted portal for contract status, payment visibility, documents, and maintenance requests.',
            'responsibilities' => ['View contract status', 'Download documents', 'Track paid and remaining rent', 'Submit maintenance requests'],
            'routes' => ['/dashboard', '/maintenance-requests'],
            'icon' => 'bi-person-badge',
        ],
    ],
    'guides' => [
        [
            'title' => 'Asset Control',
            'audience' => 'Owner / Manager',
            'route' => '/assets',
            'summary' => 'Assets are a tree. A tenant can rent a building, floor, unit, or space when that node is marked rentable.',
            'features' => ['Property/building/floor/unit hierarchy', 'Ownership and management assignment', 'Valuation and usage tracking', 'Occupancy state'],
            'steps' => ['Create the parent building', 'Add floors, units, and spaces below it', 'Mark only rentable nodes as rentable', 'Assign primary owner and manager'],
            'rules' => ['Keep codes unique', 'Do not mark parent buildings rentable unless leasing the whole building', 'Only assign managers from the same portfolio'],
            'icon' => 'bi-building',
        ],
        [
            'title' => 'Lease Lifecycle',
            'audience' => 'Owner / Manager',
            'route' => '/leases',
            'summary' => 'Leases connect a tenant to a rentable asset and generate installment balances.',
            'features' => ['Contract PDF', 'Signed upload', 'Installment generation', 'Days remaining and balance remaining'],
            'steps' => ['Create or select a tenant', 'Choose a rentable asset', 'Set rent, deposit, dates, and billing day', 'Generate the contract and installments'],
            'rules' => ['One active lease per rentable asset in v1', 'Payments should be posted to the lease, not the tenant only'],
            'icon' => 'bi-file-earmark-text',
        ],
        [
            'title' => 'Payments And Receipts',
            'audience' => 'Owner / Finance',
            'route' => '/payments',
            'summary' => 'Payments are manual in v1. Posting a payment allocates it to lease installments and feeds reports.',
            'features' => ['Rent/deposit/payment type', 'Payment method', 'Receipt PDF', 'Arrears tracking'],
            'steps' => ['Open Payments', 'Select the lease and tenant', 'Enter amount, method, date, and reference', 'Save and review the allocation in reports'],
            'rules' => ['Void bad payments instead of deleting history', 'Use references for bank transfer reconciliation'],
            'icon' => 'bi-receipt',
        ],
        [
            'title' => 'Maintenance Requests',
            'audience' => 'Tenant / Manager',
            'route' => '/maintenance-requests',
            'summary' => 'Tenants submit service requests. Owners and managers triage status, priority, assignment, notes, and cost.',
            'features' => ['Electrical/plumbing/general categories', 'Priority and status', 'Public tenant updates', 'Expense linkage'],
            'steps' => ['Tenant submits the issue', 'Owner or manager sets priority and status', 'Add public updates for the tenant', 'Record expenses and close after resolution'],
            'rules' => ['Keep internal notes private', 'Close only after tenant-visible resolution is recorded'],
            'icon' => 'bi-tools',
        ],
        [
            'title' => 'Website Control',
            'audience' => 'Superadmin',
            'route' => '/cms',
            'summary' => 'The public website is made of pages, sections, menus, and media. Sections can be reordered visually.',
            'features' => ['Bilingual pages', 'Section library', 'Drag and drop ordering', 'Header navigation'],
            'steps' => ['Create or select a page', 'Create reusable bilingual sections', 'Attach sections to the page', 'Drag sections to reorder and preview'],
            'rules' => ['Only superadmin controls the global website', 'Use predefined sections instead of raw scripts'],
            'icon' => 'bi-layout-wtf',
        ],
    ],
];
